export default [
  { romanji: 'au', japanese: 'あう', english: 'to meet', group: 'RU' },
  { romanji: 'aku', japanese: 'あく', english: 'to open', group: 'RU' },
  { romanji: 'akeru', japanese: 'あける', english: 'to open', group: 'RU' },
  { romanji: 'ageru', japanese: 'あげる', english: 'to give', group: 'U' },
  { romanji: 'asobu', japanese: 'あそぶ', english: 'to play', group: 'RU' },
  {
    romanji: 'abiru',
    japanese: 'あびる',
    english: 'to take a shower',
    group: 'RU',
  },
  { romanji: 'arau', japanese: 'あらう', english: 'to wash', group: 'RU' },
  { romanji: 'aru', japanese: 'ある', english: 'to be, to exist', group: 'RU' },
  { romanji: 'aru', japanese: 'ある', english: 'to possess', group: 'RU' },
  { romanji: 'aruku', japanese: 'あるく', english: 'to walk', group: 'RU' },
  { romanji: 'iu', japanese: 'いう', english: 'to say, to tell', group: 'RU' },
  { romanji: 'iku', japanese: 'いく', english: 'to go', group: 'RU' },
  {
    romanji: 'iru',
    japanese: 'いる',
    english: 'need, must haven be required',
    group: 'RU',
  },
  { romanji: 'iru', japanese: 'いる', english: 'to exist', group: 'RU' },
  {
    romanji: 'ireru',
    japanese: 'いれる',
    english: 'to insert, to put in',
    group: 'U',
  },
  { romanji: 'utau', japanese: 'うたう', english: 'to sing', group: 'RU' },
  {
    romanji: 'umareru',
    japanese: 'うまれる',
    english: 'to be born',
    group: 'U',
  },
  { romanji: 'uru', japanese: 'うる', english: 'to sell', group: 'RU' },
  {
    romanji: 'okiru',
    japanese: 'おきる',
    english: 'to get up, to stand up',
    group: 'RU',
  },
  { romanji: 'oku', japanese: 'おく', english: 'to put', group: 'RU' },
  { romanji: 'okuru', japanese: 'おくる', english: 'to send', group: 'OTHER' },
  { romanji: 'osu', japanese: 'おす', english: 'to push', group: 'RU' },
  {
    romanji: 'oboeru',
    japanese: 'おぼえる',
    english: 'to memorize, to remember',
    group: 'U',
  },
  { romanji: 'oyogu', japanese: 'およぐ', english: 'to swim', group: 'RU' },
  { romanji: 'oriru', japanese: 'おりる', english: 'to get off', group: 'RU' },
  { romanji: 'owaru', japanese: 'おわる', english: 'to end', group: 'RU' },
  { romanji: 'kau', japanese: 'かう', english: 'to buy', group: 'RU' },
  {
    romanji: 'kaesu',
    japanese: 'かえす',
    english: 'to return an object',
    group: 'RU',
  },
  {
    romanji: 'kaeru',
    japanese: 'かえる',
    english: 'to return home',
    group: 'RU',
  },
  {
    romanji: 'kakaru',
    japanese: 'かかる',
    english: 'to take time or money',
    group: 'RU',
  },
  { romanji: 'kaku', japanese: 'かく', english: 'to write', group: 'RU' },
  { romanji: 'kakeru', japanese: 'かける', english: 'to wear', group: 'RU' },
  {
    romanji: 'kakeru',
    japanese: 'かける',
    english: 'to make a phone call',
    group: 'RU',
  },
  { romanji: 'kasu', japanese: 'かす', english: 'to lend', group: 'RU' },
  {
    romanji: 'kaburu',
    japanese: 'かぶる',
    english: 'to put on a hat',
    group: 'RU',
  },
  { romanji: 'kariru', japanese: 'かりる', english: 'to borrow', group: 'RU' },
  {
    romanji: 'kieru',
    japanese: 'きえる',
    english: 'to go out, to vanish',
    group: 'U',
  },
  { romanji: 'kiku', japanese: 'きく', english: 'to listen', group: 'RU' },
  { romanji: 'kiru', japanese: 'きる', english: 'to cut', group: 'RU' },
  {
    romanji: 'kiru',
    japanese: 'きる',
    english: 'to wear, to put on',
    group: 'RU',
  },
  { romanji: 'kuru', japanese: 'くる', english: 'to come', group: 'OTHER' },
  {
    romanji: 'kesu',
    japanese: 'けす',
    english: 'to turn off, to switch off',
    group: 'RU',
  },
  {
    romanji: 'kotaeru',
    japanese: 'こたえる',
    english: 'to answer',
    group: 'U',
  },
  {
    romanji: 'komaru',
    japanese: 'こまる',
    english: 'to be in trouble',
    group: 'RU',
  },
  { romanji: 'saku', japanese: 'さく', english: 'to blossom', group: 'RU' },
  {
    romanji: 'sasu',
    japanese: 'さす',
    english: 'to open an umbrella',
    group: 'RU',
  },
  {
    romanji: 'shinu',
    japanese: 'しぬ',
    english: ' to die, to pass away',
    group: 'RU',
  },
  { romanji: 'shimaru', japanese: 'しまる', english: 'to close', group: 'RU' },
  { romanji: 'shimeru', japanese: 'しめる', english: 'to close', group: 'U' },
  {
    romanji: 'shimeru',
    japanese: 'しめる',
    english: 'to fasten a belt',
    group: 'U',
  },
  { romanji: 'shiru', japanese: 'しる', english: 'to know', group: 'RU' },
  {
    romanji: 'suu',
    japanese: 'すう',
    english: 'to breath, to smoke',
    group: 'RU',
  },
  {
    romanji: 'sumu',
    japanese: 'すむ',
    english: 'to live, to reside somewhere',
    group: 'RU',
  },
  { romanji: 'suru', japanese: 'する', english: 'to do', group: 'OTHER' },
  { romanji: 'suwaru', japanese: 'すわる', english: 'to sit', group: 'RU' },
  {
    romanji: 'dasu',
    japanese: 'だす',
    english: 'to take out, hand in',
    group: 'RU',
  },
  { romanji: 'tatsu', japanese: 'たつ', english: 'to stand', group: 'RU' },
  {
    romanji: 'tanomu',
    japanese: 'たのむ',
    english: 'to ask, to request',
    group: 'RU',
  },
  { romanji: 'taberu', japanese: 'たべる', english: 'to eat', group: 'U' },
  {
    romanji: 'chigau',
    japanese: 'ちがう',
    english: 'to be different',
    group: 'RU',
  },
  { romanji: 'tsukau', japanese: 'つかう', english: 'to use', group: 'RU' },
  {
    romanji: 'tsukareru',
    japanese: 'つかれる',
    english: 'to get tired',
    group: 'U',
  },
  { romanji: 'tsuku', japanese: 'つく', english: 'to arrive', group: 'RU' },
  {
    romanji: 'tsukuru',
    japanese: 'つくる',
    english: 'to make, to produce',
    group: 'OTHER',
  },
  {
    romanji: 'tsukeru',
    japanese: 'つける',
    english: 'to turn on',
    group: 'RU',
  },
  {
    romanji: 'tsutomeru',
    japanese: 'つとめる',
    english: 'to work for someone',
    group: 'U',
  },
  {
    romanji: 'dekakeru',
    japanese: 'でかける',
    english: 'to go out',
    group: 'RU',
  },
  { romanji: 'dekiru', japanese: 'できる', english: 'can do', group: 'RU' },
  { romanji: 'deru', japanese: 'でる', english: 'to leave', group: 'U' },
  { romanji: 'tobu', japanese: 'とぶ', english: 'to fly', group: 'RU' },
  { romanji: 'tomaru', japanese: 'とまる', english: 'to stop', group: 'RU' },
  { romanji: 'toru', japanese: 'とる', english: ' to take', group: 'RU' },
  {
    romanji: 'toru',
    japanese: 'とる',
    english: 'to take a photo',
    group: 'RU',
  },
  {
    romanji: 'naku',
    japanese: 'なく',
    english: 'to sing, mew, moo',
    group: 'RU',
  },
  {
    romanji: 'narabu',
    japanese: 'ならぶ',
    english: 'to form a line',
    group: 'RU',
  },
  {
    romanji: 'naraberu',
    japanese: 'ならべる',
    english: 'to line up',
    group: 'U',
  },
  { romanji: 'naru', japanese: 'なる', english: 'to become', group: 'RU' },
  {
    romanji: 'nugu',
    japanese: 'ぬぐ',
    english: 'to take off clothes',
    group: 'RU',
  },
  { romanji: 'neru', japanese: 'ねる', english: 'to sleep', group: 'U' },
  {
    romanji: 'noboru',
    japanese: 'のぼる',
    english: 'to climb up',
    group: 'RU',
  },
  { romanji: 'nomu', japanese: 'のむ', english: 'to drink', group: 'RU' },
  {
    romanji: 'noru',
    japanese: 'のる',
    english: 'to take, to ride',
    group: 'RU',
  },
  { romanji: 'hairu', japanese: 'はいる', english: 'to enter', group: 'RU' },
  {
    romanji: 'haku',
    japanese: 'はく',
    english: 'to put on shoes',
    group: 'RU',
  },
  {
    romanji: 'hajimaru',
    japanese: 'はじまる',
    english: 'to begin, to start',
    group: 'RU',
  },
  { romanji: 'hashiru', japanese: 'はしる', english: 'to run', group: 'RU' },
  {
    romanji: 'hataraku',
    japanese: 'はたらく',
    english: 'to work',
    group: 'RU',
  },
  {
    romanji: 'hanasu',
    japanese: 'はなす',
    english: 'to talk, to speak, to tell',
    group: 'RU',
  },
  {
    romanji: 'haru',
    japanese: 'はる',
    english: 'to put something on, to stick',
    group: 'RU',
  },
  { romanji: 'hareru', japanese: 'はれる', english: 'to clear up', group: 'U' },
  { romanji: 'hiku', japanese: 'ひく', english: 'to pull', group: 'RU' },
  {
    romanji: 'hiku',
    japanese: 'ひく',
    english: 'to play an instrument',
    group: 'RU',
  },
  { romanji: 'fuku', japanese: 'ふく', english: 'to blow (wind)', group: 'RU' },
  {
    romanji: 'furu',
    japanese: 'ふる',
    english: 'to fall (rain, snow)',
    group: 'RU',
  },
  { romanji: 'magaru', japanese: 'まがる', english: 'to turn', group: 'RU' },
  { romanji: 'matsu', japanese: 'まつ', english: 'to wait', group: 'RU' },
  {
    romanji: 'migaku',
    japanese: 'みがく',
    english: 'to polish, to brush',
    group: 'RU',
  },
  { romanji: 'miseru', japanese: 'みせる', english: 'to show', group: 'U' },
  {
    romanji: 'miru',
    japanese: 'みる',
    english: 'to see, to watch',
    group: 'RU',
  },
  {
    romanji: 'motsu',
    japanese: 'もつ',
    english: 'to have, to own',
    group: 'RU',
  },
  { romanji: 'yasumu', japanese: 'やすむ', english: 'to rest', group: 'RU' },
  { romanji: 'yaru', japanese: 'やる', english: ' to do', group: 'RU' },
  { romanji: 'yobu', japanese: 'よぶ', english: 'to call', group: 'RU' },
  { romanji: 'yomu', japanese: 'よむ', english: 'to read', group: 'RU' },
  {
    romanji: 'wakaru',
    japanese: 'わかる',
    english: 'to know, to understand',
    group: 'RU',
  },
  {
    romanji: 'wasureru',
    japanese: 'わすれる',
    english: 'to forget',
    group: 'U',
  },
  {
    romanji: 'watasu',
    japanese: 'わたす',
    english: 'to hand over',
    group: 'RU',
  },
  { romanji: 'wataru', japanese: 'わたる', english: 'to cross', group: 'RU' },
  { romanji: '', japanese: '', english: '', group: 'RU' },
]
